INSERT INTO QUOTE (QUOTE_AUTHOR, QUOTE_STRING, QUOTE_TYPE) VALUES ('Kanye West', 'yo mom is a bus.', 'CELEBRITY');
INSERT INTO QUOTE (QUOTE_AUTHOR, QUOTE_STRING, QUOTE_TYPE) VALUES ('Kanye West', 'LMAO.', 'CELEBRITY');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ('John', 'Lee', 'johnlee@gmail.com', 'johnlee');
INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD) VALUES ('Helen', 'Choi', 'helenchoi@hotmail.com', 'helenchoi');