CREATE TABLE QUOTE(
    QUOTE_ID BIGSERIAL PRIMARY KEY,
    QUOTE_AUTHOR VARCHAR,
    QUOTE_STRING VARCHAR,
    QUOTE_TYPE VARCHAR,
    dtype VARCHAR,
    ANIME VARCHAR
);

CREATE TABLE USERS(
    USER_NAME BIGSERIAL PRIMARY KEY,
    EMAIL VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    PASSWORD VARCHAR
);